-- ============================================================
-- Snowflake setup for AWS S3 telecom warehouse demo
-- Replace the stage URL below with:
-- terraform output -raw snowflake_stage_url
--
-- Example:
-- URL = 's3://telecom-warehouse-demo-dev-abcd1234/raw/'
-- ============================================================
CREATE DATABASE IF NOT EXISTS TELECOM_WAREHOUSE_DEMO;

CREATE SCHEMA IF NOT EXISTS TELECOM_WAREHOUSE_DEMO.RAW;

CREATE SCHEMA IF NOT EXISTS TELECOM_WAREHOUSE_DEMO.ANALYTICS;

CREATE WAREHOUSE IF NOT EXISTS TELECOM_DEMO_XS_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE TELECOM_DEMO_XS_WH;

USE DATABASE TELECOM_WAREHOUSE_DEMO;

USE SCHEMA RAW;

CREATE
OR REPLACE FILE FORMAT CSV_FORMAT TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF = ('', 'NULL', 'null');

CREATE
OR REPLACE STAGE TELECOM_S3_STAGE URL = 's3://REPLACE_WITH_YOUR_BUCKET/raw/' FILE_FORMAT = CSV_FORMAT;

CREATE
OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME STRING,
    COUNTRY STRING,
    SEGMENT STRING,
    PLAN_TYPE STRING,
    SIGNUP_DATE DATE,
    STATUS STRING
);

CREATE
OR REPLACE TABLE USAGE_RECORDS (
    USAGE_ID NUMBER,
    CUSTOMER_ID NUMBER,
    BILLING_MONTH STRING,
    DATA_GB NUMBER,
    VOICE_MINUTES NUMBER,
    SMS_COUNT NUMBER
);

CREATE
OR REPLACE TABLE BILLING (
    INVOICE_ID STRING,
    CUSTOMER_ID NUMBER,
    BILLING_MONTH STRING,
    TOTAL_AMOUNT NUMBER(12, 2),
    PAYMENT_STATUS STRING,
    PAYMENT_DATE DATE
);

CREATE
OR REPLACE TABLE SUPPORT_TICKETS (
    TICKET_ID STRING,
    CUSTOMER_ID NUMBER,
    CREATED_DATE DATE,
    SEVERITY STRING,
    STATUS STRING,
    RESOLUTION_HOURS NUMBER,
    CATEGORY STRING
);

COPY INTO CUSTOMERS
FROM
    @TELECOM_S3_STAGE / customers.csv FILE_FORMAT = CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';

COPY INTO USAGE_RECORDS
FROM
    @TELECOM_S3_STAGE / usage_records.csv FILE_FORMAT = CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';

COPY INTO BILLING
FROM
    @TELECOM_S3_STAGE / billing.csv FILE_FORMAT = CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';

COPY INTO SUPPORT_TICKETS
FROM
    @TELECOM_S3_STAGE / support_tickets.csv FILE_FORMAT = CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';

USE SCHEMA ANALYTICS;

CREATE
OR REPLACE VIEW VW_MONTHLY_REVENUE AS
SELECT
    BILLING_MONTH,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
    SUM(
        CASE
            WHEN PAYMENT_STATUS = 'Paid' THEN TOTAL_AMOUNT
            ELSE 0
        END
    ) AS COLLECTED_REVENUE,
    SUM(
        CASE
            WHEN PAYMENT_STATUS IN ('Pending', 'Overdue') THEN TOTAL_AMOUNT
            ELSE 0
        END
    ) AS OUTSTANDING_REVENUE,
    ROUND(
        SUM(
            CASE
                WHEN PAYMENT_STATUS = 'Paid' THEN TOTAL_AMOUNT
                ELSE 0
            END
        ) / NULLIF(SUM(TOTAL_AMOUNT), 0) * 100,
        2
    ) AS COLLECTION_RATE_PERCENT
FROM
    RAW.BILLING
GROUP BY
    BILLING_MONTH;

CREATE
OR REPLACE VIEW VW_CUSTOMER_REVENUE AS
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.COUNTRY,
    C.SEGMENT,
    C.PLAN_TYPE,
    C.STATUS,
    SUM(B.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM
    RAW.CUSTOMERS C
    JOIN RAW.BILLING B ON C.CUSTOMER_ID = B.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.COUNTRY,
    C.SEGMENT,
    C.PLAN_TYPE,
    C.STATUS;

CREATE
OR REPLACE VIEW VW_USAGE_SUMMARY AS
SELECT
    U.BILLING_MONTH,
    C.SEGMENT,
    SUM(U.DATA_GB) AS TOTAL_DATA_GB,
    SUM(U.VOICE_MINUTES) AS TOTAL_VOICE_MINUTES,
    SUM(U.SMS_COUNT) AS TOTAL_SMS_COUNT
FROM
    RAW.USAGE_RECORDS U
    JOIN RAW.CUSTOMERS C ON U.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    U.BILLING_MONTH,
    C.SEGMENT;

CREATE
OR REPLACE VIEW VW_SUPPORT_METRICS AS
SELECT
    SEVERITY,
    STATUS,
    COUNT(*) AS TICKET_COUNT,
    AVG(RESOLUTION_HOURS) AS AVG_RESOLUTION_HOURS
FROM
    RAW.SUPPORT_TICKETS
GROUP BY
    SEVERITY,
    STATUS;

CREATE
OR REPLACE VIEW VW_EXECUTIVE_KPIS AS
SELECT
    (
        SELECT
            COUNT(*)
        FROM
            RAW.CUSTOMERS
    ) AS TOTAL_CUSTOMERS,
    (
        SELECT
            COUNT(*)
        FROM
            RAW.CUSTOMERS
        WHERE
            STATUS = 'Active'
    ) AS ACTIVE_CUSTOMERS,
    (
        SELECT
            SUM(TOTAL_AMOUNT)
        FROM
            RAW.BILLING
    ) AS TOTAL_BILLED_AMOUNT,
    (
        SELECT
            SUM(TOTAL_AMOUNT)
        FROM
            RAW.BILLING
        WHERE
            PAYMENT_STATUS = 'Paid'
    ) AS TOTAL_COLLECTED_AMOUNT,
    (
        SELECT
            SUM(DATA_GB)
        FROM
            RAW.USAGE_RECORDS
    ) AS TOTAL_DATA_GB,
    (
        SELECT
            COUNT(*)
        FROM
            RAW.SUPPORT_TICKETS
    ) AS TOTAL_SUPPORT_TICKETS;